#pragma once
#include "nlohmann/json.hpp"

enum class TileType
{
	None = 0,
	Abyss = 1,
	Ocean = 2,
	IceLand = 3,
	Shore = 4,
	SnowyShore = 5,
	Plains = 6,
	FireLand = 7,
	Forest = 8,
	Tundra = 9,
	Desert = 10,
	GrassyHill = 11,
	ForestHill = 12,
	MuddyHill = 13,
	DryHill = 14,
	SnowyHill = 15,
	DesertDunes = 16,
	Volcano = 17,
	RockyMountain = 18,
	IceMountain = 19,
	Swamp = 20,
	RainForest = 21,
	DryLand = 22,
	Savannah = 23,
	GeyserLand = 24,
};
NLOHMANN_JSON_SERIALIZE_ENUM(TileType, {
	{TileType::None, "None"},
	{TileType::Abyss, "Abyss"},
	{TileType::Ocean, "Ocean"},
	{TileType::IceLand, "IceLand"},
	{TileType::Shore, "Shore"},
	{TileType::SnowyShore, "SnowyShore"},
	{TileType::Plains, "Plains"},
	{TileType::FireLand, "FireLand"},
	{TileType::Forest, "Forest"},
	{TileType::Tundra, "Tundra"},
	{TileType::Desert, "Desert"},
	{TileType::GrassyHill, "GrassyHill"},
	{TileType::ForestHill, "ForestHill"},
	{TileType::MuddyHill, "MuddyHill"},
	{TileType::DryHill, "DryHill"},
	{TileType::SnowyHill, "SnowyHill"},
	{TileType::DesertDunes, "DesertDunes"},
	{TileType::Volcano, "Volcano"},
	{TileType::RockyMountain, "RockyMountain"},
	{TileType::IceMountain, "IceMountain"},
	{TileType::Swamp, "Swamp"},
	{TileType::RainForest, "RainForest"},
	{TileType::DryLand, "DryLand"},
	{TileType::Savannah, "Savannah"},
	{TileType::GeyserLand, "GeyserLand"}
	});