#pragma once

enum class TileType
{
	None = 0,
	Abyss = 1,
	Ocean = 2,
	IceLand = 3,
	Shore = 4,
	SnowyShore = 5,
	Plains = 6,
	FireLand = 7,
	Forest = 8,
	Tundra = 9,
	Desert = 10,
	GrassyHill = 11,
	ForestHill = 12,
	MuddyHill = 13,
	DryHill = 14,
	SnowyHill = 15,
	DesertDunes = 16,
	Volcano = 17,
	RockyMountain = 18,
	IceMountain = 19,
	Swamp = 20,
	RainForest = 21,
	DryLand = 22,
	Savannah = 23,
	GeyserLand = 24,
};